#!/bin/sh

    SDKBuildPackageDEB() {
        if [ -x /usr/bin/dpkg ]; then
            dpkg -l dpkg-dev | grep "^ii" | grep "dpkg-dev" > /dev/null || SDKExitFatal "Package 'dpkg-dev' not installed"
            dpkg -l debhelper | grep "^ii" | grep "debhelper" > /dev/null || SDKExitFatal "Package 'debhelper' not installed"
          else
            echo "Warning: no check for packages performed"
        fi
        # apt-get install dpkg-dev
        # apt-get install debhelper
        echo "Building DEB"
        dpkg-buildpackage -b -us -uc
        SDKShowLine
    }

    SDKBuildPackageRPM() {
        echo "Building RPM"
        if [ -x /usr/bin/dpkg ]; then
            dpkg -l rpm | grep "^ii" | grep "rpm" > /dev/null || SDKExitFatal "Package 'rpm' not installed"
          else
            echo "Warning: no check for packages performed"
        fi
        DIRS="BUILD BUILDROOT RPMS SOURCES SRPMS"
        for DIR in ${DIRS}; do
            if [ ! -d ~/leenus-build/rpmbuild/${DIR} ]; then mkdir -p ~/leenus-build/rpmbuild/${DIR}; fi
        done
        ls -l ./tmp/leenus-build/rpmbuild
        tar --create -z -f ~/leenus-build/rpmbuild/SOURCES/leenus-${LEENUS_VERSION}.tar.gz ../leenus/*
        SDKShowLine
        ls -l ./tmp/leenus-build/rpmbuild/SOURCES/leenus-${LEENUS_VERSION}.tar.gz
        SDKShowLine
        rpmbuild -ba ./package-building/leenus.spec
        SDKShowLine
    }

    SDKExitFatal() {
        echo "Fatal error: $1"
        exit 1
    }

    SDKShowLine() {
        echo "==============================================================="
    }

    SDKPrintFailed() {
        printf " FAILED\n"
    }

    SDKPrintOK() {
        printf " OK\n"
    }


# EOF
